[package]
name = "libcrypto"
version = "0.1.0"
authors = ["Lukas Renner"]
edition = "2021"
readme = "./README.md"
keywords = ["crypto"]
license = "Apache-2.0"
description = "a collection of cryptographic functions"
